services:
  db:
    profiles:
      - dev
      - prod
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testapp
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app
  keycloak:
    profiles:
      - dev
    ports:
      - 8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev --http-host=0.0.0.0 --import-realm
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - app
  minio:
    profiles:
      - dev
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
      - "45199:45199"
    environment:
      MINIO_ROOT_USER: minioadmin
      VIRTUAL_PORT: 9000
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app
  app:
    profiles:
      - dev
      - prod
    image: ghcr.io/grnd-alt/cial:main
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=testapp
      - APP_ENV=development
      - APP_PORT=8000
      - OIDC_ISSUER=http://keycloak:8080/realms/goapp
      - OIDC_CLIENT_ID=testapplication
      - JWT_SECRET=secret
      - S3_URL=minio:9000
      - S3_ACCESS=minioadmin
      - S3_SECRET=minioadmin
      - S3_BUCKET_NAME=testbucket
    depends_on:
      - db
    networks:
      - app
volumes:
  pg_data:
  minio_data:
networks:
  app:
    driver: bridge